server:
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ainu
    username: admin
    password: pdpano
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: H5E0x7IWTHBQI95D06v8rMCdQ2HFqTROc654ieno88FqUBCj9zTAcD9qGzZgG69