CREATE TABLE IF NOT EXISTS tb_users (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	birth DATE NOT NULL,
	email VARCHAR NOT NULL UNIQUE,
	cpf VARCHAR NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT NOW()
);